# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_predict.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DlgPredict(object):
    def setupUi(self, DlgPredict):
        DlgPredict.setObjectName("DlgPredict")
        DlgPredict.resize(597, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgPredict.sizePolicy().hasHeightForWidth())
        DlgPredict.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(DlgPredict)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.groupSettings = QtWidgets.QGroupBox(DlgPredict)
        self.groupSettings.setObjectName("groupSettings")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupSettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbxImageryLayer = QtWidgets.QComboBox(self.groupSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxImageryLayer.sizePolicy().hasHeightForWidth())
        self.cbxImageryLayer.setSizePolicy(sizePolicy)
        self.cbxImageryLayer.setObjectName("cbxImageryLayer")
        self.gridLayout_2.addWidget(self.cbxImageryLayer, 0, 2, 1, 1)
        self.lblImageryLayer = QtWidgets.QLabel(self.groupSettings)
        self.lblImageryLayer.setObjectName("lblImageryLayer")
        self.gridLayout_2.addWidget(self.lblImageryLayer, 0, 0, 1, 1)
        self.lblAddRawPredictions = QtWidgets.QLabel(self.groupSettings)
        self.lblAddRawPredictions.setObjectName("lblAddRawPredictions")
        self.gridLayout_2.addWidget(self.lblAddRawPredictions, 1, 0, 1, 1)
        self.chkAddPlainPredictions = QtWidgets.QCheckBox(self.groupSettings)
        self.chkAddPlainPredictions.setChecked(True)
        self.chkAddPlainPredictions.setObjectName("chkAddPlainPredictions")
        self.gridLayout_2.addWidget(self.chkAddPlainPredictions, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupSettings, 0, 0, 1, 5)
        self.grpPreview = QtWidgets.QGroupBox(DlgPredict)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPreview.sizePolicy().hasHeightForWidth())
        self.grpPreview.setSizePolicy(sizePolicy)
        self.grpPreview.setObjectName("grpPreview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grpPreview)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblPreviewText = QtWidgets.QLabel(self.grpPreview)
        self.lblPreviewText.setWordWrap(True)
        self.lblPreviewText.setObjectName("lblPreviewText")
        self.gridLayout_3.addWidget(self.lblPreviewText, 0, 0, 1, 1)
        self.lblImage = QtWidgets.QLabel(self.grpPreview)
        self.lblImage.setObjectName("lblImage")
        self.gridLayout_3.addWidget(self.lblImage, 2, 0, 1, 1)
        self.btnRefresh = QtWidgets.QPushButton(self.grpPreview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout_3.addWidget(self.btnRefresh, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.grpPreview, 1, 0, 1, 5)
        self.btnPredict = QtWidgets.QPushButton(DlgPredict)
        self.btnPredict.setObjectName("btnPredict")
        self.gridLayout.addWidget(self.btnPredict, 3, 4, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(DlgPredict)
        self.btnCancel.setMinimumSize(QtCore.QSize(80, 0))
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 3)

        self.retranslateUi(DlgPredict)
        self.btnCancel.clicked.connect(DlgPredict.reject)
        self.btnPredict.clicked.connect(DlgPredict.accept)
        QtCore.QMetaObject.connectSlotsByName(DlgPredict)

    def retranslateUi(self, DlgPredict):
        _translate = QtCore.QCoreApplication.translate
        DlgPredict.setWindowTitle(_translate("DlgPredict", "Prediction"))
        self.groupSettings.setTitle(_translate("DlgPredict", "Settings"))
        self.lblImageryLayer.setText(_translate("DlgPredict", "Imagery Layer"))
        self.lblAddRawPredictions.setText(_translate("DlgPredict", "Predictions"))
        self.chkAddPlainPredictions.setText(_translate("DlgPredict", "Add the predictions as-is from the neural network. Otherwise, only the changes will be shown."))
        self.grpPreview.setTitle(_translate("DlgPredict", "Preview"))
        self.lblPreviewText.setText(_translate("DlgPredict", "The following image will be sent to the backend. Make sure, there are no white areas visible, otherwise click the refresh button."))
        self.lblImage.setText(_translate("DlgPredict", "Preview is loading..."))
        self.btnRefresh.setText(_translate("DlgPredict", "Refresh"))
        self.btnPredict.setText(_translate("DlgPredict", "Predict"))
        self.btnCancel.setText(_translate("DlgPredict", "Cancel"))

